#version: '3.9'

services:
  db:
    image: mysql:8.3.0
    container_name: mysql_server_project4_network
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: network_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  
  web:
    container_name: web_server_network
    build: .
    volumes: 
      - ./:/usr/src/app/
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore: 
            - LICENCE
            - README.md
        - action: rebuild
          path: ./requirements.txt
          target: /usr/src/app/requirements.txt
        - action: rebuild
          path: ./wait-for-db.sh
          target: /usr/src/app/wait-for-db.sh
    ports: 
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: