#version: '3.9'

services:
  db:
    image: mysql:8.3.0
    container_name: mysql_server_project4_network
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: network_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    

  
  web:
    build: .
    ports: 
      - "8000:8000"

volumes:
  mysql_data: