# Generated by Django 5.2 on 2025-04-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createt_at',
            new_name='created_at',
        ),
    ]
