# Generated by Django 5.2 on 2025-04-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_createt_at_post_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
